name: yarn-upgrade-minor 
id : update

on:
  schedule:
  - cron: "23 20 1-31 * *" 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm i yarn
      - run: yarn
      - run: yarn yarn-upgrade-minor --non-interactive

name: Notification
  uses: rtCamp/action-slack-notify@master
  uses: dawidd6/action-send-mail@v3
  with:
    # Required mail server address:
    server_address: smtp.gmail.com
    # Required mail server port:
    server_port: 465
    # Optional (recommended): mail server username:
    username: ${{secrets.MAIL_USERNAME}}
    # Optional (recommended) mail server password:
    password: ${{secrets.MAIL_PASSWORD}}
    # Required mail subject:
    subject: Github Actions job result
    # Required recipients' addresses:
    to: ${{secrets.MAIL_TO}}
    # Required sender full name (address can be skipped):
    from: GIT # <user@example.com>
    # Optional whether this connection use TLS (default is true if server_port is 465)
    secure: true
    # Optional plain body:
    body: Build job of ${{github.repository}} completed successfully! \n ${{ steps.update.outputs.stdout }} 
    # Optional unsigned/invalid certificates allowance:
    ignore_cert: true
    # Optional priority: 'high', 'normal' (default) or 'low'
    priority: low